@isTEST
public class TestTimeRecordReminder {
      /*public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    public static testmethod void test1(){
         Test.startTest();
	   String jobId = System.schedule('ScheduleApexClassTest',CRON_EXP,new TimeRecordReminder());
        
    Account a = new Account();
    a.Name='test';
    insert a;
       
    
        
    Policy__c p = new Policy__c ();
    p.Account_Policy__c=a.id;
    p.Name='637428';
    p.Term__c='semi';
    insert p;
        
     Policy__c p2 = new Policy__c ();
    p2.Account_Policy__c=a.id;
    p2.Name='637428';
    p2.Term__c='daily';
    insert p2;
        
         Policy__c p21 = new Policy__c ();
    p21.Account_Policy__c=a.id;
    p21.Name='637428';
    p21.Term__c='daily';
    insert p21;

    
    Contact c = new Contact();
    c.LastName='testt';
    c.AccountId=a.id;
    c.Email='abc@gamil.com';
    insert c;
      id tempId ;
    tempId = [select id, name from EmailTemplate where name=  'Loyal Client Feedback'].id;  
       
       
        Test.stopTest();
}*/
}