@isTest
public class TestMethodWrapperClassTest {
    @isTest
    static void testMehodForWrapperClass(){
        
        Test.startTest();
        PopulatePayementWrapper objectName  = new PopulatePayementWrapper();
         objectName.MapfreData = null;
         objectName.qualitasData = null;
         objectName.ChubbData = null;
        objectName.days = 89;
        
        PopulatePayementWrapper.ChubbData chubData = new PopulatePayementWrapper.ChubbData();
        chubData.BajaSonaraDiscountComplete = null;
        chubData.BajaSonaraDiscountLiabilityOnly = null;
        chubData.brokerFee = null;
        chubData.CompleteCoveragePremium = null;
        chubData.DamageDeductible = null;
        chubData.LegalandRoadside = null;
        chubData.Liability = null;
        chubData.LiabilityOnlyPremium = null;
        chubData.Medical = null;
        chubData.PhysicalDamage = null;
        chubData.PlatinumEndorsementCompleteCoverage = null;
        chubData.PlatinumEndorsementLiabilityOnly = null;
        chubData.showChubb = true;
        chubData.TotalCompleteCoverage = null;
        chubData.TotalPremiumLiabilityOnly = null;
        chubData.TotalPremiumLiabilityOnly = null;
        chubData.TotalTheft = null;
        chubData.TowedUnitPhysicalDamage = null;
        chubData.TowedUnitTotalTheft = null;
        
        PopulatePayementWrapper.PhysicalDamage PhysicalDamageobjectName  = new PopulatePayementWrapper.PhysicalDamage();
        PhysicalDamageobjectName.Semi_annual = 67;
        PhysicalDamageobjectName.Annual = 67;
        PhysicalDamageobjectName.Daily = 12;
        
        PopulatePayementWrapper.ageSurcharge ageSurchargeobjectName  = new PopulatePayementWrapper.ageSurcharge();
        ageSurchargeobjectName.Annual = 87;
        ageSurchargeobjectName.Daily = 45;
        ageSurchargeobjectName.Semi_annual = 155;
        
        PopulatePayementWrapper.BajaSonaraDiscountComplete BajaSonaraDiscountCompleteobjectName  = new PopulatePayementWrapper.BajaSonaraDiscountComplete();
        BajaSonaraDiscountCompleteobjectName.Annual =90;
        BajaSonaraDiscountCompleteobjectName.Daily = 78;
        BajaSonaraDiscountCompleteobjectName.Semi_annual = 90;
        
        
        PopulatePayementWrapper.BajaSonaraDiscountLiabilityOnly liblityComObject = new PopulatePayementWrapper.BajaSonaraDiscountLiabilityOnly();
        liblityComObject.Annual=78;
        liblityComObject.Daily=90;
        liblityComObject.Semi_annual = 78;
        
        
        PopulatePayementWrapper.brokerFee brokerFeeObject = new PopulatePayementWrapper.brokerFee();
        brokerFeeObject.Annual = 90;
        brokerFeeObject.Daily = 90;
        brokerFeeObject.Days180 = 90;
        brokerFeeObject.Days90 = 90;
        brokerFeeObject.Semi_annual = 90;
        
        PopulatePayementWrapper.businessSurcharge bussObject = new PopulatePayementWrapper.businessSurcharge();
        bussObject.Annual = 90;
        bussObject.Daily = 90;
        bussObject.Semi_annual = 90;
        
        PopulatePayementWrapper.CompleteCoverageLimited comLimited = new PopulatePayementWrapper.CompleteCoverageLimited();
        comLimited.Annual = 90;
        comLimited.Daily = 90;
        comLimited.Semi_annual = 90;
        
        PopulatePayementWrapper.CompleteCoveragePremium priumObject = new PopulatePayementWrapper.CompleteCoveragePremium();
        priumObject.Annual = 90;
        priumObject.Daily = 90;
        priumObject.Semi_annual = 90;
        
        PopulatePayementWrapper.DamageDeductible dedectObject = new PopulatePayementWrapper.DamageDeductible();
        dedectObject.Annual = 90;
        dedectObject.Daily = 90;
        dedectObject.Semi_annual  =0;
        
        PopulatePayementWrapper.deductiblesPhysicalDamages phyObject = new PopulatePayementWrapper.deductiblesPhysicalDamages();
        phyObject.Annual = 90;
        phyObject.Daily = 90;
        phyObject.Days180 = 90;
        phyObject.Days90 = 90;
        
        PopulatePayementWrapper.deductiblesTotalTheft dameTotThObject = new PopulatePayementWrapper.deductiblesTotalTheft();
        dameTotThObject.Annual = 90;
        dameTotThObject.Daily = 90;
        dameTotThObject.Days180 = 90;
        dameTotThObject.Days90 = 90;
        
        PopulatePayementWrapper.fullCoverageTotal fulCovObject = new PopulatePayementWrapper.fullCoverageTotal();
        fulCovObject.Annual = 0;
        fulCovObject.Daily = 89;
        fulCovObject.Days180 = 90;
        fulCovObject.Days90 = 90;
        
        PopulatePayementWrapper.IVACompleteCoverage IVAcomCovObject= new PopulatePayementWrapper.IVACompleteCoverage();
        IVAcomCovObject.Annual = 90; 
        IVAcomCovObject.Daily = 90;
        IVAcomCovObject.Semi_annual = 90;
        
        PopulatePayementWrapper.IVAFullCoverage  IVAFullObje = new PopulatePayementWrapper.IVAFullCoverage();
        IVAFullObje.Annual = 90;
        IVAFullObje.Daily = 90;
        IVAFullObje.Days180 = 90;
        IVAFullObje.Days90 = 90;
        
        PopulatePayementWrapper.IVALiabilityOnly IVALIbObject = new PopulatePayementWrapper.IVALiabilityOnly();
        IVALIbObject.Annual = 90;
        IVALIbObject.Daily = 90;
        IVALIbObject.Semi_annual = 90;
        
        PopulatePayementWrapper.IVAliabilityOnlyTotal IVALIBTotObject = new PopulatePayementWrapper.IVAliabilityOnlyTotal();
        IVALIBTotObject.Annual = 90;
        IVALIBTotObject.Daily = 90;
        IVALIBTotObject.Days180 = 90;
        IVALIBTotObject.Days90 = 90;
        
        PopulatePayementWrapper.IVALimitedCoverage IVALIMCOVObject = new PopulatePayementWrapper.IVALimitedCoverage();
        IVALIMCOVObject.Annual = 90;
        IVALIMCOVObject.Daily = 90;
        IVALIMCOVObject.Semi_annual = 90;
        
        PopulatePayementWrapper.LegalandRoadside legalRoadObject = new PopulatePayementWrapper.LegalandRoadside();
        legalRoadObject.Annual = 90;
        legalRoadObject.Daily = 90;
        legalRoadObject.Semi_annual = 90;
        
        PopulatePayementWrapper.legalAssist leageAssObject = new PopulatePayementWrapper.legalAssist();
        leageAssObject.Annual = 90;
        leageAssObject.Daily = 90;
        leageAssObject.Days180 = 90;
        leageAssObject.Days90 = 90;
        
        PopulatePayementWrapper.Liability Liability = new PopulatePayementWrapper.Liability();
        Liability.Annual = 90;
        Liability.Daily = 90;
        Liability.Days180 = 90;
        Liability.Days90 = 90;
        Liability.Semi_annual = 90;
        
        PopulatePayementWrapper.LiabilityOnlyLimitedTerritory LiabilityOnlyLimitedTerritory = new PopulatePayementWrapper.LiabilityOnlyLimitedTerritory();
        LiabilityOnlyLimitedTerritory.Annual = 90;
        LiabilityOnlyLimitedTerritory.Daily = 90;
        LiabilityOnlyLimitedTerritory.Semi_annual = 90;
        
        
        PopulatePayementWrapper.LiabilityOnlyPremium LiabilityOnlyPremium = new PopulatePayementWrapper.LiabilityOnlyPremium();
        LiabilityOnlyPremium.Annual = 90;
        LiabilityOnlyPremium.Daily = 90;
        LiabilityOnlyPremium.Semi_annual = 90;
        
        PopulatePayementWrapper.liabilityOnlyTotal liabilityOnlyTotal = new PopulatePayementWrapper.liabilityOnlyTotal();
        liabilityOnlyTotal.Annual = 90;
        liabilityOnlyTotal.Daily = 90;
        liabilityOnlyTotal.Days180 = 90;
        liabilityOnlyTotal.Days90 = 90;
        
        PopulatePayementWrapper.limitedCoverageTotal limitedCoverageTotal = new PopulatePayementWrapper.limitedCoverageTotal();
        limitedCoverageTotal.Annual = 90;
        limitedCoverageTotal.Daily = 90;
        limitedCoverageTotal.Days180 = 90;
        limitedCoverageTotal.Days90 = 90;
        
        PopulatePayementWrapper.MaxCoverageTotal MaxCoverageTotal = new PopulatePayementWrapper.MaxCoverageTotal();
        MaxCoverageTotal.Annual = 90;
        MaxCoverageTotal.Daily = 90;
        MaxCoverageTotal.Days180 = 90;
        MaxCoverageTotal.Days90 = 90;
        
        PopulatePayementWrapper.Medical Medical = new PopulatePayementWrapper.Medical();
        Medical.Annual = 90;
        Medical.Daily = 90;
        Medical.Semi_annual = 90;
        
        PopulatePayementWrapper.medicalPayments medicalpayment = new PopulatePayementWrapper.medicalPayments();
        medicalpayment.Annual = 90;
        medicalpayment.Daily = 90;
        medicalpayment.Days180 = 90;
        medicalpayment.Days90 = 90;
        
        PopulatePayementWrapper.PhysicalDamage PhysicalDamage = new PopulatePayementWrapper.PhysicalDamage();
        PhysicalDamage.Annual = 90;
        PhysicalDamage.Daily = 90;
        PhysicalDamage.Semi_annual = 90;
        
        PopulatePayementWrapper.physicalDamages physicalDamages = new PopulatePayementWrapper.physicalDamages();
        physicalDamages.Annual = 90;
        physicalDamages.Daily = 90;
        physicalDamages.Days180 = 90;
        physicalDamages.Days90 = 90;
        
        PopulatePayementWrapper.PlatinumEndorsementCompleteCoverage PlatinumEndorsementCompleteCoverage = new PopulatePayementWrapper.PlatinumEndorsementCompleteCoverage();
        PlatinumEndorsementCompleteCoverage.Annual = 90;
        PlatinumEndorsementCompleteCoverage.Daily = 90;
        PlatinumEndorsementCompleteCoverage.Semi_annual = 90;
        
        PopulatePayementWrapper.PlatinumEndorsementLiabilityOnly pletinumLib = new PopulatePayementWrapper.PlatinumEndorsementLiabilityOnly();
        pletinumLib.Annual = 90;
        pletinumLib.Daily = 90;
        pletinumLib.Semi_annual = 90;
        
        PopulatePayementWrapper.TheftDeductible theftDeduct = new PopulatePayementWrapper.TheftDeductible();
        theftDeduct.Annual = 90;
        theftDeduct.Daily = 90;
        theftDeduct.Semi_annual = 90;
        
        PopulatePayementWrapper.TotalCompleteCoverage totalCover = new PopulatePayementWrapper.TotalCompleteCoverage();
        totalCover.Annual = 90;
        totalCover.Daily = 90;
        totalCover.Semi_annual = 90;
        
        PopulatePayementWrapper.TotalPremiumLiabilityOnly  totalPremLib = new PopulatePayementWrapper.TotalPremiumLiabilityOnly();
        totalPremLib.Annual = 90;
        totalPremLib.Daily = 90;
        totalPremLib.Semi_annual = 90;
        
        PopulatePayementWrapper.TotalTheft totalTheft = new PopulatePayementWrapper.TotalTheft();
        totalTheft.Annual = 90;
        totalTheft.Daily = 90;
        totalTheft.Days180 = 90;
        totalTheft.Days90 = 90;
        totalTheft.Semi_annual = 90;
        
        
        PopulatePayementWrapper.TowedUnitPhysicalDamage TowedUnitPhysicalDamage = new PopulatePayementWrapper.TowedUnitPhysicalDamage();
        TowedUnitPhysicalDamage.Annual = 90;
        TowedUnitPhysicalDamage.Daily = 90;
        TowedUnitPhysicalDamage.Semi_annual = 0;
        
        PopulatePayementWrapper.TowedUnitTotalTheft totalTheftUnit = new PopulatePayementWrapper.TowedUnitTotalTheft();
        totalTheftUnit.Daily = 90;
        
        PopulatePayementWrapper.travelAssistance totalAsssistence = new PopulatePayementWrapper.travelAssistance();
        totalAsssistence.Annual = 90;
        totalAsssistence.Daily = 90;
        totalAsssistence.Days180 = 90;
        totalAsssistence.Days90 = 90;
        
       // PopulatePayementWrapper 
        
        
        
        
        
        
        
        
        
        
        
        Test.stopTest();
    }
}